name: Unit tests
run-name: Running unit tests

on:
  pull_request:
    branches:
      - main
      - master

permissions:
  contents: read

jobs:
  test:
    name: 'Unit Tests'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run unit tests
        run: yarn test
